export const ActionTypes = {
  HALL_OF_FAME_FOUND: "HALL_OF_FAME_FOUND",
  HALL_OF_FAME_CLEARED: "HALL_OF_FAME_CLEARED",

  PLAYER_FOUND: "PLAYER_FOUND",
  PLAYER_DETAILS_CLEARED: "PLAYER_DETAILS_CLEARED",

  SIGNUP_PLAYER: "SIGNUP_PLAYER",
  SIGNIN_PLAYER: "SIGNIN_PLAYER",
  PLAYER_HAS_LOGGED_OUT: "PLAYER_HAS_LOGGED_OUT",
  CLEAR_LOG: "CLEAR_LOG",
  
  DELAY_FINISHED: 'DELAY_FINISHED',
  PLAYER_FETCHED_WITH_TOKEN: "PLAYER_FETCHED_WITH_TOKEN",
  NO_PLAYER_FETCHED_WITH_TOKEN: "NO_PLAYER_FETCHED_WITH_TOKEN",

  PLAYERS_FOUND: "PLAYERS_FOUND",
  FILTER_UPDATED: "FILTER_UPDATED",
  FILTER_UPDATED_RETURNED_TO_PAGE_ONE: "FILTER_UPDATED_RETURNED_TO_PAGE_ONE",
  FILTER_RESETED: "FILTER_RESETED",

  EDIT_PLAYER: "EDIT_PLAYER",
  CLEAR_EDIT_PLAYER: "CLEAR_EDIT_PLAYER",

  EMAIL_SENT_TO_RECOVER_PASSWORD: "EMAIL_SENT_TO_RECOVER_PASSWORD",
  PASSWORD_MODAL_CLEARED: "PASSWORD_MODAL_CLEARED",
  PASSWORD_RECOVERED: "PASSWORDS_RECOVERED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  ENABLE_CREATE_BY_ADMIN: "ENABLE_CREATE_BY_ADMIN",
  CREATE_PLAYER_BY_ADMIN: "CREATE_PLAYER_BY_ADMIN",
  CLEAR_STORE_PLAYER_CREATED: "CLEAR_STORE_PLAYER_CREATED"
}