export const ActionTypes = {
  HALL_OF_FAME_FOUND: "HALL_OF_FAME_FOUND",
  HALL_OF_FAME_CLEARED: "HALL_OF_FAME_CLEARED",

  PLAYER_FOUND: "PLAYER_FOUND",
  PLAYER_DETAILS_CLEARED: "PLAYER_DETAILS_CLEARED",

  SIGNUP_PLAYER: "SIGNUP_PLAYER",
  SIGNIN_PLAYER: "SIGNIN_PLAYER",
  PLAYER_HAS_LOGGED_OUT: "PLAYER_HAS_LOGGED_OUT",

  PLAYERS_FOUND: "PLAYERS_FOUND",
  FILTER_UPDATED: "FILTER_UPDATED",
  FILTER_UPDATED_RETURNED_TO_PAGE_ONE: "FILTER_UPDATED_RETURNED_TO_PAGE_ONE",
  FILTER_RESETED: "FILTER_RESETED",

  EDIT_PLAYER: "EDIT_PLAYER",
  CLEAR_EDIT_PLAYER: "CLEAR_EDIT_PLAYER",

  EMAIL_SENT_TO_RECOVER_PASSWORD: "EMAIL_SENT_TO_RECOVER_PASSWORD",
  PASSWORD_MODAL_CLEARED: "PASSWORD_MODAL_CLEARED",
  PASSWORD_RECOVERED: "PASSWORDS_RECOVERED"
}