export const ActionTypes = {
  PLAYER_FOUND: "PLAYER_FOUND",
  PLAYER_DETAILS_CLEARED: "PLAYER_DETAILS_CLEARED",
  SIGNUP_PLAYER: "SIGNUP_PLAYER",

  PLAYERS_FOUND: "PLAYERS_FOUND",
  FILTER_UPDATED: "FILTER_UPDATED",
  FILTER_UPDATED_RETURNED_TO_PAGE_ONE: "FILTER_UPDATED_RETURNED_TO_PAGE_ONE"
}